In [1]:
import numpy as np

In [3]:
list1 = [1,2,4,2,5]
list2 = [3,9,4,2,5]
np.array(list1)+np.array(list2)

array([ 4, 11,  8,  4, 10])

In [4]:
arr_str = ['Meercedes',6,'Audi','Ferrari','Tesla']
arr_num = (5,4,6,3,7)

In [5]:
print(type(arr_str))
print(type(arr_num))

<class 'list'>
<class 'tuple'>


In [6]:
np_arr_str = np.array(arr_str)
np_arr_num = np.array(arr_num)

In [7]:
print(type(np_arr_str))
print(type(np_arr_num))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [8]:
matrix1 = np.array([(1,2),[3,4],(5,6)])
matrix1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
type(matrix1)

numpy.ndarray

In [10]:
matrix1.shape

(3, 2)

In [14]:
arr2 = np.arange(0,10,3)
arr2

array([0, 3, 6, 9])

In [16]:
matrix2 = np.linspace(0,10,13)
matrix2

array([ 0.        ,  0.83333333,  1.66666667,  2.5       ,  3.33333333,
        4.16666667,  5.        ,  5.83333333,  6.66666667,  7.5       ,
        8.33333333,  9.16666667, 10.        ])

In [17]:
matrix3 = np.linspace(11,20,10)
matrix3

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [19]:
matrix4 = np.zeros([5,3])
matrix4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
matrix5 = np.ones([5,3])
matrix5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
arr3 = np.arange(0,32)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [23]:
arr3.shape

(32,)

In [36]:
arr3 = arr3.reshape(1,32)
print(arr3.shape)
print(arr3)

(1, 32)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31]]


In [37]:
arr3 = arr3.reshape(2,16)
print(arr3.shape)
print(arr3)

(2, 16)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]]


In [38]:
arr3 = arr3.reshape(4,8)
print(arr3.shape)
print(arr3)

(4, 8)
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


In [39]:
arr3 = arr3.reshape(8,4)
print(arr3.shape)
print(arr3)

(8, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [40]:
arr3 = arr3.reshape(16,2)
print(arr3.shape)
print(arr3)

(16, 2)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]]


In [41]:
arr3 = arr3.reshape(32,1)
print(arr3.shape)
print(arr3)

(32, 1)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]]
